[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mts"
version = "0.1.0"
description = "Minimal music theory scaffolding"
authors = [{name = "Tonality"}]
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.optional-dependencies]
qt = [
    "PySide6>=6.8.0.2,<6.11",
]

[tool.setuptools.packages.find]
include = ["mts*"]
exclude = ["tests*"]

[project.urls]
Homepage = "https://example.com"
